from typing import Protocol


class ObjectStorage(Protocol):
    def upload_bytes(self, key: str, data: bytes, content_type: str) -> str: ...

    def delete(self, key: str) -> None: ...

    def download_bytes(self, key: str) -> bytes: ...

    def generate_presigned_url(self, key: str, expires: int = 3600) -> str: ...
